CREATE TABLE departments
(
    id                int8 generated by default as identity,
    name              varchar(255)  not null,
    description       varchar(255) not null,
    phone_number      varchar(255)  not null,
    date_of_formation timestamp    not null,

    primary key (id)
);

CREATE TABLE employees
(
    id                 int8 generated by default as identity,
    full_name          varchar(255),
    date_of_birth      timestamp   not null,
    phone_number       varchar(255) not null,
    email_address      varchar(255) not null,
    position           varchar(30) not null,
    date_of_employment timestamp   not null,
    department_id      int8 default null,

    primary key (id),
    foreign key (department_id) references departments (id)
);

insert into departments (name, description, phone_number, date_of_formation)
values ('QA Department', 'QA Department', '55-89-89', '2015-03-15');

insert into departments (name, description, phone_number, date_of_formation)
values ('Backend Department', 'Backend Department', '55-89-90', '2015-03-14');

insert into departments (name, description, phone_number, date_of_formation)
values ('Frontend Department', 'Frontend Department', '55-89-91', '2015-03-14');

insert into employees (full_name, date_of_birth, phone_number, email_address, position, date_of_employment, department_id)
values ('Sergey Sergeev', '1989-08-07', '+37529-532-65-31', 'signatuk89@gmail.com', 'Java Developer', '2016-10-14', 2);

insert into employees (full_name, date_of_birth, phone_number, email_address, position, date_of_employment, department_id)
values ('Natalya Sergeeva', '1989-04-04', '+37529-671-81-08', 'natalinifox@gmail.com', 'QA', '2017-05-25', 1);

insert into employees (full_name, date_of_birth, phone_number, email_address, position, date_of_employment, department_id)
values ('Olga Romanova', '1989-10-20', '+37529-571-48-51', 'okuriga@gmail.com', 'Java Developer', '2016-07-20', 2);

insert into employees (full_name, date_of_birth, phone_number, email_address, position, date_of_employment, department_id)
values ('Nikolai Nikolaev', '1988-03-20', '+37529-640-04-64', 'nikolaev@gmail.com', 'Project Manager', '2015-03-20', null);